name: Daily Idea Reminder

on:
  schedule:
    - cron: "0 11 * * *"

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        USERNAME: ${{ secrets.USERNAME }}
      run: python reminder.py

    - name: Delete workflow run
      uses: peter-evans/delete-workflow-runs@v2.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow_id: ${{ github.workflow }}
        retention_days: 3
